// <auto-generated />
using System;
using DemoDB.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoDB.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20180814043304_ninthCreate")]
    partial class ninthCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DemoDB.Model.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BillName");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("CreatorId");

                    b.Property<int>("GroupId");

                    b.Property<byte[]>("Image");

                    b.HasKey("BillId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("GroupId");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("DemoDB.Model.BillMember", b =>
                {
                    b.Property<int>("BillMemberId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AmountToPay");

                    b.Property<int>("Billid");

                    b.Property<int>("SharedMemberId");

                    b.HasKey("BillMemberId");

                    b.HasIndex("Billid");

                    b.HasIndex("SharedMemberId");

                    b.ToTable("BillMember");
                });

            modelBuilder.Entity("DemoDB.Model.FriendList", b =>
                {
                    b.Property<int>("FriendListId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FriendId");

                    b.Property<int>("UserId");

                    b.HasKey("FriendListId");

                    b.HasIndex("FriendId");

                    b.HasIndex("UserId");

                    b.ToTable("FriendList");
                });

            modelBuilder.Entity("DemoDB.Model.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("CreatorId");

                    b.Property<string>("GroupName");

                    b.HasKey("GroupId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("DemoDB.Model.GroupMember", b =>
                {
                    b.Property<int>("GroupMemberId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Group_Id");

                    b.Property<int>("User_Id");

                    b.HasKey("GroupMemberId");

                    b.HasIndex("Group_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("GroupMember");
                });

            modelBuilder.Entity("DemoDB.Model.GroupPayer", b =>
                {
                    b.Property<int>("GroupPayerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BillId");

                    b.Property<decimal>("PaidAmount");

                    b.Property<int>("PayerId");

                    b.HasKey("GroupPayerId");

                    b.HasIndex("BillId");

                    b.HasIndex("PayerId");

                    b.ToTable("GroupPayer");
                });

            modelBuilder.Entity("DemoDB.Model.IndividualPayer", b =>
                {
                    b.Property<int>("IndividualPayerid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BillId");

                    b.Property<decimal>("PaidAmount");

                    b.Property<int>("PayerId");

                    b.HasKey("IndividualPayerid");

                    b.HasIndex("BillId");

                    b.HasIndex("PayerId");

                    b.ToTable("IndividualPayer");
                });

            modelBuilder.Entity("DemoDB.Model.Settlement", b =>
                {
                    b.Property<int>("SettlementId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PayerId");

                    b.Property<int>("SharedMemberId");

                    b.HasKey("SettlementId");

                    b.HasIndex("PayerId");

                    b.HasIndex("SharedMemberId");

                    b.ToTable("Settlement");
                });

            modelBuilder.Entity("DemoDB.Model.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GroupId");

                    b.Property<decimal>("PaidAmount");

                    b.Property<int>("PayerId");

                    b.Property<int>("ReceiverId");

                    b.Property<int?>("payersIdUserId");

                    b.Property<int?>("receiversIdUserId");

                    b.HasKey("TransactionId");

                    b.HasIndex("GroupId");

                    b.HasIndex("payersIdUserId");

                    b.HasIndex("receiversIdUserId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("DemoDB.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DemoDB.Model.Bill", b =>
                {
                    b.HasOne("DemoDB.Model.User", "User")
                        .WithMany("Bills")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DemoDB.Model.Group", "Group")
                        .WithMany("Bills")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DemoDB.Model.BillMember", b =>
                {
                    b.HasOne("DemoDB.Model.Bill", "Bill")
                        .WithMany()
                        .HasForeignKey("Billid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DemoDB.Model.User", "User")
                        .WithMany("BillMembers")
                        .HasForeignKey("SharedMemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DemoDB.Model.FriendList", b =>
                {
                    b.HasOne("DemoDB.Model.User", "friend")
                        .WithMany("Friends")
                        .HasForeignKey("FriendId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DemoDB.Model.User", "user")
                        .WithMany("Users")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DemoDB.Model.Group", b =>
                {
                    b.HasOne("DemoDB.Model.User", "User")
                        .WithMany("Groups")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DemoDB.Model.GroupMember", b =>
                {
                    b.HasOne("DemoDB.Model.Group", "Group")
                        .WithMany("groupMembers")
                        .HasForeignKey("Group_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DemoDB.Model.User", "User")
                        .WithMany("groupMembers")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DemoDB.Model.GroupPayer", b =>
                {
                    b.HasOne("DemoDB.Model.Bill", "Bill")
                        .WithMany("GroupPayers")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DemoDB.Model.User", "User")
                        .WithMany("GroupPayers")
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DemoDB.Model.IndividualPayer", b =>
                {
                    b.HasOne("DemoDB.Model.Bill", "Bill")
                        .WithMany("IndividualPayers")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DemoDB.Model.User", "User")
                        .WithMany("IndividualPayers")
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DemoDB.Model.Settlement", b =>
                {
                    b.HasOne("DemoDB.Model.User", "Payer")
                        .WithMany("Payers")
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DemoDB.Model.User", "SharedMember")
                        .WithMany("SharedMembers")
                        .HasForeignKey("SharedMemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DemoDB.Model.Transaction", b =>
                {
                    b.HasOne("DemoDB.Model.Group", "groupsId")
                        .WithMany("Transactions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DemoDB.Model.User", "payersId")
                        .WithMany("PayersId")
                        .HasForeignKey("payersIdUserId");

                    b.HasOne("DemoDB.Model.User", "receiversId")
                        .WithMany("ReceiversId")
                        .HasForeignKey("receiversIdUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
